import { money, number } from '../../utils/format.js';

const factor = (value) => value === 'INFINITY' ? '∞' : value == null ? '—' : number(value, 2);
const metric = (row, key, currency) => key.includes('Trade') || key === 'netProfitLoss' || key === 'averageWin' || key === 'averageLoss' ? money(key.includes('Trade') ? row[key]?.profitLoss : row[key], currency) : key === 'winRate' ? `${number(row[key], 2)}%` : factor(row[key]);

export default function PerformanceBreakdown({ rows, currency, sort, setSort, onSelect }) {
  const columns = [['netProfitLoss', 'Net P&L'], ['totalTrades', 'Trades'], ['winRate', 'Win rate'], ['profitFactor', 'Profit factor']];
  const sortValue = (row) => row[sort] === 'INFINITY' ? Number.POSITIVE_INFINITY : Number(row[sort] ?? Number.NEGATIVE_INFINITY);
  const sorted = [...rows].sort((a, b) => sortValue(b) - sortValue(a) || a.name.localeCompare(b.name));
  return <section className="card overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-line p-4"><div><h3 className="font-semibold">Performance breakdown</h3><p className="mt-1 text-xs text-muted">Click a category to open its matching journal trades.</p></div><label className="flex items-center gap-2 text-xs text-muted">Sort by <select className="field w-36 py-1.5 text-xs" value={sort} onChange={(event) => setSort(event.target.value)}>{columns.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label></div>
    <div className="hidden overflow-x-auto lg:block"><table className="w-full min-w-[1180px] text-left text-xs"><thead className="bg-white/[.025] text-muted"><tr>{['Category', 'Trades', 'Net P&L', 'Win rate', 'Wins', 'Losses', 'BE', 'Avg win', 'Avg loss', 'Profit factor', 'Best', 'Worst'].map((label) => <th className="px-3 py-3 font-medium" key={label}>{label}</th>)}</tr></thead><tbody className="divide-y divide-line">{sorted.map((row) => <tr className="cursor-pointer hover:bg-white/[.035]" key={row.key} onClick={() => onSelect(row)}><td className="px-3 py-3 font-medium text-white">{row.name}</td><td className="px-3 py-3">{row.totalTrades}</td><td className={row.netProfitLoss >= 0 ? 'px-3 py-3 text-lime' : 'px-3 py-3 text-rose-400'}>{money(row.netProfitLoss, currency)}</td><td className="px-3 py-3">{row.winRate == null ? '—' : `${number(row.winRate, 2)}%`}</td><td className="px-3 py-3">{row.wins}</td><td className="px-3 py-3">{row.losses}</td><td className="px-3 py-3">{row.breakEven}</td><td className="px-3 py-3">{metric(row, 'averageWin', currency)}</td><td className="px-3 py-3">{metric(row, 'averageLoss', currency)}</td><td className="px-3 py-3">{factor(row.profitFactor)}</td><td className="px-3 py-3">{metric(row, 'bestTrade', currency)}</td><td className="px-3 py-3">{metric(row, 'worstTrade', currency)}</td></tr>)}</tbody></table></div>
    <div className="grid gap-3 p-4 lg:hidden">{sorted.map((row) => <button className="rounded-xl border border-line p-4 text-left hover:bg-white/[.035]" key={row.key} onClick={() => onSelect(row)}><div className="flex items-start justify-between gap-3"><span className="font-semibold">{row.name}</span><span className={row.netProfitLoss >= 0 ? 'text-lime' : 'text-rose-400'}>{money(row.netProfitLoss, currency)}</span></div><div className="mt-3 grid grid-cols-2 gap-2 text-xs text-muted"><span>{row.totalTrades} trades</span><span>{row.winRate == null ? '—' : `${number(row.winRate, 2)}%`} win rate</span><span>{row.wins}W · {row.losses}L · {row.breakEven}BE</span><span>PF {factor(row.profitFactor)}</span></div></button>)}</div>
  </section>;
}
