import { useEffect, useMemo, useState } from 'react';
import { useHistory } from 'react-router-dom';
import { Archive, RotateCcw, Search, WalletCards } from 'lucide-react';
import { api, errorMessage } from '../api/client.js';
import { money, number } from '../utils/format.js';
import { deleteAccountAndRefresh } from '../utils/accountDeletion.js';
import AccountModal from '../components/account/AccountModal.jsx';
import AccountsCenterLayout from '../components/account/AccountsCenterLayout.jsx';
import ConfirmModal from '../components/ui/ConfirmModal.jsx';
import Toast from '../components/ui/Toast.jsx';

export default function AccountsCenter() {
  const [accounts, setAccounts] = useState([]), [metrics, setMetrics] = useState({}), [search, setSearch] = useState(''), [type, setType] = useState(''), [status, setStatus] = useState('');
  const [modal, setModal] = useState(null), [confirmation, setConfirmation] = useState(null), [deleteConfirmation, setDeleteConfirmation] = useState(null);
  const [error, setError] = useState(''), [busy, setBusy] = useState(false), [toast, setToast] = useState(null);
  const history = useHistory();
  const load = async () => { try { const { data } = await api.get('/accounts', { params: { includeArchived: true } }); setAccounts(data.data); const pairs = await Promise.all(data.data.map(async (account) => { const phase = account.accountType === 'FUNDED' ? (account.phases.find((item) => item.status === 'ACTIVE') || account.phases[0]) : null; try { const response = await api.get(`/accounts/${account.id}/statistics`, { params: phase ? { phaseId: phase.id } : {} }); return [account.id, response.data.data]; } catch { return [account.id, null]; } })); setMetrics(Object.fromEntries(pairs)); } catch (e) { setError(errorMessage(e)); } };
  useEffect(() => { load(); }, []);
  const filtered = useMemo(() => accounts.filter((account) => (!search || account.name.toLowerCase().includes(search.toLowerCase())) && (!type || account.accountType === type) && (!status || account.status === status)), [accounts, search, type, status]);
  const active = accounts.filter((account) => account.status !== 'ARCHIVED'), currencies = [...new Set(active.map((account) => account.currency))];
  const totalTrades = active.reduce((sum, account) => sum + (metrics[account.id]?.totalTrades || 0), 0), best = active.filter((account) => metrics[account.id]).sort((a, b) => (metrics[b.id].netProfitLoss / Number(b.initialCapital || 1)) - (metrics[a.id].netProfitLoss / Number(a.initialCapital || 1)))[0];
  const save = async (form) => { setBusy(true); try { modal === 'create' ? await api.post('/accounts', form) : await api.patch(`/accounts/${modal.id}`, form); setModal(null); await load(); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } };
  const confirmArchive = async () => { if (!confirmation) return; setBusy(true); try { await api.post(`/accounts/${confirmation.id}/${confirmation.status === 'ARCHIVED' ? 'restore' : 'archive'}`); setConfirmation(null); await load(); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } };
  const confirmDelete = async () => { if (!deleteConfirmation) return; const deleted = deleteConfirmation; setBusy(true); setError(''); try { const message = await deleteAccountAndRefresh({ api, accountId: deleted.id, removeLocally: (id) => { setAccounts((current) => current.filter((account) => account.id !== id)); setMetrics((current) => { const next = { ...current }; delete next[id]; return next; }); setDeleteConfirmation(null); setModal(null); if (localStorage.getItem('activeAccountId') === String(id)) localStorage.removeItem('activeAccountId'); }, refresh: load }); setToast({ message: message || 'Account deleted successfully', type: 'success' }); } catch (e) { const message = errorMessage(e); setError(message); setToast({ message, type: 'error' }); } finally { setBusy(false); } };
  const open = (account, phase) => { localStorage.setItem('activeAccountId', String(account.id)); history.push(`/?accountId=${account.id}${phase ? `&phaseId=${phase.id}` : ''}`); };

  return <AccountsCenterLayout section="accounts" showAdd onAdd={() => setModal('create')}><main className="mx-auto max-w-[1500px] space-y-5 px-6 py-7">
    {error && <div className="rounded-xl border border-rose-500/30 p-3 text-rose-400">{error}</div>}
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-6">{[['Total Accounts', accounts.length], ['Active Accounts', active.length], ['Combined Balance', currencies.length === 1 ? money(active.reduce((sum, account) => sum + (metrics[account.id]?.currentBalance || Number(account.initialCapital)), 0), currencies[0]) : 'Mixed currencies'], ['Combined Net P&L', currencies.length === 1 ? money(active.reduce((sum, account) => sum + (metrics[account.id]?.netProfitLoss || 0), 0), currencies[0]) : 'Mixed currencies'], ['Total Trades', totalTrades], ['Best Account', best?.name || '—']].map(([label, value]) => <article className="card p-4" key={label}><p className="text-xs uppercase tracking-wider text-muted">{label}</p><p className="mt-2 text-xl font-semibold">{value}</p></article>)}</section>
    <section className="card flex flex-wrap gap-3 p-4"><div className="relative min-w-64 flex-1"><Search className="absolute left-3 top-2.5 text-muted" size={17}/><input className="field pl-9" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search accounts…"/></div><select className="field w-40" value={type} onChange={(event) => setType(event.target.value)}><option value="">All types</option><option value="REAL">Real</option><option value="FUNDED">Funded</option></select><select className="field w-44" value={status} onChange={(event) => setStatus(event.target.value)}><option value="">All statuses</option>{['ACTIVE', 'PAUSED', 'PASSED', 'FAILED', 'CLOSED', 'ARCHIVED'].map((item) => <option key={item}>{item}</option>)}</select></section>
    <section className="grid items-stretch gap-4 lg:grid-cols-2 xl:grid-cols-3">{filtered.map((account) => { const stat = metrics[account.id], phase = account.phases?.find((item) => item.status === 'ACTIVE'); return <article className="card flex h-full flex-col gap-5 p-5" key={account.id}>
      <div className="flex-1"><div className="flex justify-between gap-3"><div><p className="text-lg font-semibold">{account.name}</p><p className="mt-1 text-xs text-muted">{account.accountType === 'FUNDED' ? 'Funded Account' : 'Real Account'} · {account.propFirm || account.broker || 'No broker set'}</p>{phase && <p className="mt-1 text-xs text-lime">{phase.name} — Active</p>}</div><span className="h-fit rounded bg-white/5 px-2 py-1 text-xs">{account.status || 'ACTIVE'}</span></div>
      <div className="mt-5 grid grid-cols-2 gap-3 text-sm">{[['Initial Balance', money(account.initialCapital, account.currency)], ['Current Balance', money(stat?.currentBalance ?? account.initialCapital, account.currency)], ['Net P&L', money(stat?.netProfitLoss || 0, account.currency)], ['Return', `${number((stat?.netProfitLoss || 0) / Number(account.initialCapital || 1) * 100, 2)}%`], ['Trades', stat?.totalTrades || 0], ['Win Rate', `${number(stat?.winRate || 0, 2)}%`]].map(([label, value]) => <div key={label}><p className="text-xs text-muted">{label}</p><p className="mt-1 font-medium">{value}</p></div>)}</div></div>
      <div className="mt-auto flex flex-wrap gap-2 border-t border-line pt-4"><button className="btn-primary" onClick={() => open(account, phase)}>Open Journal</button><button className="btn-secondary" onClick={() => setModal(account)}>Manage</button><button className="btn-secondary" onClick={() => setConfirmation(account)}>{account.status === 'ARCHIVED' ? <RotateCcw size={15}/> : <Archive size={15}/>} {account.status === 'ARCHIVED' ? 'Restore' : 'Archive'}</button></div>
    </article>; })}</section>
    {!filtered.length && <div className="card flex min-h-48 items-center justify-center text-muted"><WalletCards className="mr-2"/> No accounts match these filters.</div>}
  </main>
  <AccountModal open={!!modal} account={modal === 'create' ? null : modal} onClose={() => setModal(null)} onSave={save} onDelete={() => setDeleteConfirmation(modal)} busy={busy}/>
  <ConfirmModal isOpen={!!confirmation} title={`${confirmation?.status === 'ARCHIVED' ? 'Restore' : 'Archive'} ${confirmation?.name}?`} message="Trades and analytics will remain preserved." confirmLabel={confirmation?.status === 'ARCHIVED' ? 'Restore account' : 'Archive account'} variant={confirmation?.status === 'ARCHIVED' ? 'SUCCESS' : 'WARNING'} isLoading={busy} onConfirm={confirmArchive} onCancel={() => setConfirmation(null)}/>
  <ConfirmModal isOpen={!!deleteConfirmation} title={`Delete ${deleteConfirmation?.name || 'account'}?`} message="This permanently deletes the account and all of its related journal data, including funded phases, trades, analytics data, and screenshots. This cannot be undone." confirmLabel="Delete account" variant="DANGER" isLoading={busy} onConfirm={confirmDelete} onCancel={() => setDeleteConfirmation(null)}/>
  <Toast toast={toast} onClose={() => setToast(null)}/>
  </AccountsCenterLayout>;
}
