import { useCallback, useEffect, useMemo, useState } from 'react';
import { BarChart3, RotateCcw, WalletCards } from 'lucide-react';
import { Link, useHistory, useLocation } from 'react-router-dom';
import { api, errorMessage } from '../api/client.js';
import { money, number } from '../utils/format.js';
import { BREAKDOWN_BY_TAB, journalDrillDownUrl, PERFORMANCE_TABS, performanceQuery } from '../utils/performanceNavigation.js';
import BalanceChart from '../components/chart/BalanceChart.jsx';
import OutcomeDistribution from '../components/performance/OutcomeDistribution.jsx';
import PerformanceBreakdown from '../components/performance/PerformanceBreakdown.jsx';
import PerformanceMetricCard from '../components/performance/PerformanceMetricCard.jsx';

const factor = (value) => value === 'INFINITY' ? '∞' : value == null ? '—' : number(value, 2);
const title = (tab) => tab[0].toUpperCase() + tab.slice(1);

export default function PerformanceCenter() {
  const location = useLocation(), history = useHistory(), query = useMemo(() => new URLSearchParams(location.search), [location.search]);
  const tabParam = query.get('tab'), tab = PERFORMANCE_TABS.includes(tabParam) ? tabParam : 'overview';
  const [accounts, setAccounts] = useState([]), [accountId, setAccountId] = useState(null), [phaseId, setPhaseId] = useState(null);
  const [from, setFrom] = useState(query.get('from') || ''), [to, setTo] = useState(query.get('to') || ''), [data, setData] = useState(null);
  const [loading, setLoading] = useState(true), [error, setError] = useState(''), [retryKey, setRetryKey] = useState(0), [sort, setSort] = useState('netProfitLoss');
  const account = accounts.find((item) => item.id === accountId), phases = account?.phases || [], phase = phases.find((item) => item.id === phaseId);

  useEffect(() => { api.get('/accounts').then(({ data: response }) => { const rows = response.data; setAccounts(rows); const requested = Number(query.get('accountId') || localStorage.getItem('activeAccountId')); setAccountId(rows.some((item) => item.id === requested) ? requested : rows[0]?.id || null); }).catch((reason) => setError(errorMessage(reason))).finally(() => setLoading(false)); }, []);
  useEffect(() => { if (!account) return; if (account.accountType === 'FUNDED') { const requested = Number(query.get('phaseId')); setPhaseId(account.phases.some((item) => item.id === requested) ? requested : account.phases.find((item) => item.status === 'ACTIVE')?.id || account.phases[0]?.id || null); } else setPhaseId(null); }, [account?.id]);
  useEffect(() => { setFrom(query.get('from') || ''); setTo(query.get('to') || ''); }, [location.search]);
  const syncUrl = useCallback((next = {}) => { const state = { tab, accountId, phaseId, from, to, ...next }; history.push(`/performance?${performanceQuery(state)}`); }, [tab, accountId, phaseId, from, to, history]);
  useEffect(() => { if (!accountId || account?.accountType === 'FUNDED' && !phaseId) return; let active = true; setLoading(true); setError(''); const params = { ...(phaseId ? { phaseId } : {}), from: from || undefined, to: to || undefined, breakdown: BREAKDOWN_BY_TAB[tab] }; api.get(`/accounts/${accountId}/performance`, { params }).then(({ data: response }) => { if (active) setData(response.data); }).catch((reason) => { if (active) setError(errorMessage(reason)); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [accountId, phaseId, account?.accountType, from, to, tab, retryKey]);
  const selectAccount = (value) => { const id = Number(value), selected = accounts.find((item) => item.id === id); localStorage.setItem('activeAccountId', String(id)); setAccountId(id); const nextPhase = selected?.accountType === 'FUNDED' ? selected.phases.find((item) => item.status === 'ACTIVE')?.id || selected.phases[0]?.id : null; setPhaseId(nextPhase || null); syncUrl({ accountId: id, phaseId: nextPhase || null }); };
  const selectPhase = (value) => { const id = Number(value); setPhaseId(id); syncUrl({ phaseId: id }); };
  const changeDate = (key, value) => { key === 'from' ? setFrom(value) : setTo(value); syncUrl({ [key]: value }); };
  const clear = () => { setFrom(''); setTo(''); syncUrl({ from: '', to: '' }); };
  const openCategory = (row) => history.push(journalDrillDownUrl({ accountId, phaseId, from, to, journalFilter: row.journalFilter }));
  const summary = data?.summary, currency = data?.scope.currency || account?.currency;
  const cards = summary ? [['Net P&L', money(summary.netProfitLoss, currency)], ['Total trades', summary.totalTrades], ['Win rate', summary.winRate == null ? '—' : `${number(summary.winRate, 2)}%`], ['Profit factor', factor(summary.profitFactor)], ['Average win', summary.averageWin == null ? '—' : money(summary.averageWin, currency)], ['Average loss', summary.averageLoss == null ? '—' : money(summary.averageLoss, currency)], ['Best trade', summary.bestTrade ? money(summary.bestTrade.profitLoss, currency) : '—'], ['Worst trade', summary.worstTrade ? money(summary.worstTrade.profitLoss, currency) : '—']] : [];

  return <div className="min-h-screen bg-[radial-gradient(circle_at_20%_0%,rgba(199,243,107,.05),transparent_24%)]"><header className="border-b border-line bg-ink/80"><div className="mx-auto flex max-w-[1700px] flex-wrap items-center justify-between gap-4 px-5 py-4 lg:px-8"><Link to="/" className="flex items-center gap-3"><img src="/yb-journal-logo.png" alt="YB-Journal logo" className="h-14 w-14 object-contain"/><div><h1 className="font-semibold"><span className="text-lime">YB</span>-Journal</h1><p className="text-xs text-muted">Performance Center</p></div></Link><nav className="flex gap-2"><Link className="btn-secondary" to={`/journal?${new URLSearchParams({ ...(accountId ? { accountId } : {}), ...(phaseId ? { phaseId } : {}) })}`}>Journal</Link><Link className="btn-secondary" to="/accounts">Accounts Center</Link></nav></div></header>
    <main className="mx-auto max-w-[1700px] space-y-5 px-5 py-7 lg:px-8"><section className="flex flex-col justify-between gap-4 xl:flex-row xl:items-end"><div><p className="text-xs font-medium uppercase tracking-[.2em] text-lime">Analytics</p><h2 className="mt-2 text-3xl font-semibold">Performance Center</h2><p className="mt-2 text-sm text-muted">Reliable realized results for one account and phase at a time.</p></div><div className="flex flex-wrap items-end gap-3"><div><label className="label">Active account</label><select className="field min-w-52" value={accountId || ''} onChange={(event) => selectAccount(event.target.value)}>{accounts.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></div>{account?.accountType === 'FUNDED' && <div><label className="label">Active phase</label><select className="field min-w-44" value={phaseId || ''} onChange={(event) => selectPhase(event.target.value)}>{phases.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></div>}<div><label className="label">From</label><input type="date" className="field w-40" value={from} onChange={(event) => changeDate('from', event.target.value)}/></div><div><label className="label">To</label><input type="date" className="field w-40" value={to} onChange={(event) => changeDate('to', event.target.value)}/></div><button className="btn-secondary" onClick={clear}><RotateCcw size={15}/> Clear filters</button></div></section>
      {!accounts.length && !loading ? <section className="card flex min-h-72 flex-col items-center justify-center p-8 text-center"><WalletCards size={40} className="text-lime"/><h3 className="mt-4 text-lg font-semibold">No trading account available</h3><Link className="btn-primary mt-4" to="/accounts">Open Accounts Center</Link></section> : <>
      <nav className="flex gap-2 overflow-x-auto pb-1">{PERFORMANCE_TABS.map((item) => <button className={tab === item ? 'btn-primary shrink-0' : 'btn-secondary shrink-0'} key={item} onClick={() => syncUrl({ tab: item })}>{title(item)}</button>)}</nav>
      {error ? <section className="card border-rose-500/30 p-6 text-center"><p className="text-rose-400">{error}</p><button className="btn-secondary mt-4" onClick={() => setRetryKey((value) => value + 1)}>Retry</button></section> : loading || !data ? <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{Array.from({ length: 8 }, (_, index) => <div className="card h-24 animate-pulse bg-white/[.025]" key={index}/>)}</section> : !summary.totalTrades ? <section className="card flex min-h-72 flex-col items-center justify-center p-8 text-center"><BarChart3 size={40} className="text-lime"/><h3 className="mt-4 text-lg font-semibold">No realized trades in this period</h3><p className="mt-2 text-sm text-muted">Change or clear the date range to review performance.</p></section> : tab === 'overview' ? <><section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{cards.map(([label, value]) => <PerformanceMetricCard key={label} label={label} value={value}/>)}</section><div className="grid gap-4 xl:grid-cols-[minmax(0,2fr)_minmax(320px,1fr)]"><BalanceChart data={data.balanceHistory} currency={currency} loading={false} scaleKey={`${accountId}-${phaseId}-${from}-${to}`}/><OutcomeDistribution summary={summary}/></div></> : <PerformanceBreakdown rows={data.breakdown} currency={currency} sort={sort} setSort={setSort} onSelect={openCategory}/>}</>}
    </main></div>;
}
