import { useEffect, useMemo, useState } from 'react';
import { useHistory, useLocation } from 'react-router-dom';
import { CalendarDays, ChevronLeft, ChevronRight } from 'lucide-react';
import { api, errorMessage } from '../api/client.js';
import ActiveAccountIndicator from '../components/account/ActiveAccountIndicator.jsx';
import MissingActiveAccount from '../components/account/MissingActiveAccount.jsx';
import PerformanceChartTooltip from '../components/performance/PerformanceChartTooltip.jsx';
import DayTradeDrawer from '../components/trade/DayTradeDrawer.jsx';
import { useActiveAccount } from '../context/ActiveAccountContext.jsx';
import { money, number } from '../utils/format.js';
import { journalDrillDownUrl } from '../utils/performanceNavigation.js';

const DAY_NAMES=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
const pad=(value)=>String(value).padStart(2,'0');
const dateKey=(date)=>`${date.getFullYear()}-${pad(date.getMonth()+1)}-${pad(date.getDate())}`;
const monthKey=(date)=>`${date.getFullYear()}-${pad(date.getMonth()+1)}`;
const parseMonth=(value)=>/^\d{4}-\d{2}$/.test(value||'')?new Date(Number(value.slice(0,4)),Number(value.slice(5))-1,1):new Date(new Date().getFullYear(),new Date().getMonth(),1);
const pnl=(trade)=>Number(trade.profitLoss)||0;

function summarize(trades){
  const wins=trades.filter((trade)=>trade.result==='WIN'),losses=trades.filter((trade)=>trade.result==='LOSS'),breakEven=trades.filter((trade)=>trade.result==='BREAK_EVEN');
  const net=trades.reduce((sum,trade)=>sum+pnl(trade),0),ordered=[...trades].sort((a,b)=>pnl(a)-pnl(b));
  return {trades:trades.length,net,wins:wins.length,losses:losses.length,breakEven:breakEven.length,winRate:wins.length+losses.length?wins.length/(wins.length+losses.length)*100:null,bestTrade:ordered.at(-1)||null,worstTrade:ordered[0]||null,averageWin:wins.length?wins.reduce((sum,trade)=>sum+pnl(trade),0)/wins.length:null,averageLoss:losses.length?losses.reduce((sum,trade)=>sum+pnl(trade),0)/losses.length:null};
}

function calendarData(month,trades){
  const year=month.getFullYear(),monthIndex=month.getMonth(),daysInMonth=new Date(year,monthIndex+1,0).getDate(),leading=(new Date(year,monthIndex,1).getDay()+6)%7;
  const grouped=new Map();
  for(const trade of trades){const key=String(trade.tradeDate).slice(0,10);if(!grouped.has(key))grouped.set(key,[]);grouped.get(key).push(trade)}
  const days=Array.from({length:daysInMonth},(_,index)=>{const date=new Date(year,monthIndex,index+1),key=dateKey(date),dayTrades=grouped.get(key)||[];return {date,key,day:index+1,...summarize(dayTrades)}});
  const cells=[...Array.from({length:leading},()=>null),...days];while(cells.length%7)cells.push(null);
  const weeks=Array.from({length:cells.length/7},(_,index)=>{const weekDays=cells.slice(index*7,index*7+7).filter(Boolean),weekTrades=weekDays.flatMap((day)=>grouped.get(day.key)||[]),summary=summarize(weekTrades),tradingDays=weekDays.filter((day)=>day.trades);return {...summary,index:index+1,days:weekDays,tradingDays:tradingDays.length,bestDay:[...tradingDays].sort((a,b)=>b.net-a.net)[0]||null,worstDay:[...tradingDays].sort((a,b)=>a.net-b.net)[0]||null}});
  return {days,cells,weeks};
}

function MetricCard({label,value,tone}){return <article className="card min-h-24 p-4"><p className="text-xs uppercase tracking-wider text-muted">{label}</p><p className={`mt-2 text-lg font-semibold ${tone==='profit'?'text-lime':tone==='loss'?'text-rose-400':''}`}>{value}</p></article>}

function DayTooltip({day,currency}){
  if(!day)return null;
  return <PerformanceChartTooltip active payload={[{payload:day,value:day.net}]} title={day.date.toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'long',year:'numeric'})} color={day.net>0?'#c7f36b':day.net<0?'#fb7185':'#64748b'}>
    {[['Trades',day.trades],['Net P&L',money(day.net,currency)],['Win Rate',day.winRate==null?'—':`${number(day.winRate,1)}%`],['Wins',day.wins],['Losses',day.losses],['Break-even trades',day.breakEven],['Best Trade',day.bestTrade?money(pnl(day.bestTrade),currency):'—'],['Worst Trade',day.worstTrade?money(pnl(day.worstTrade),currency):'—'],['Average Win',day.averageWin==null?'—':money(day.averageWin,currency)],['Average Loss',day.averageLoss==null?'—':money(day.averageLoss,currency)]].map(([label,value])=><div className="performance-chart-tooltip__row" key={label}><span>{label}</span><strong className={label.includes('Loss')?'text-rose-400':label.includes('P&L')&&day.net>=0?'text-lime':''}>{value}</strong></div>)}
  </PerformanceChartTooltip>
}

export default function TradingCalendar(){
  const history=useHistory(),location=useLocation(),{activeAccountId:accountId,activeAccount:account,activePhaseId:phaseId}=useActiveAccount();
  const [month,setMonth]=useState(()=>parseMonth(new URLSearchParams(location.search).get('month'))),[trades,setTrades]=useState([]),[loading,setLoading]=useState(false),[error,setError]=useState(''),[hovered,setHovered]=useState(null),[selectedDayKey,setSelectedDayKey]=useState(null);
  const from=dateKey(new Date(month.getFullYear(),month.getMonth(),1)),to=dateKey(new Date(month.getFullYear(),month.getMonth()+1,0)),currency=account?.currency||'USD';
  useEffect(()=>{const params=new URLSearchParams(location.search);params.set('month',monthKey(month));if(accountId)params.set('accountId',accountId);if(phaseId)params.set('phaseId',phaseId);history.replace(`/calendar?${params}`)},[month,accountId,phaseId]);
  useEffect(()=>setSelectedDayKey(null),[accountId,phaseId,from,to]);
  useEffect(()=>{if(!accountId||account?.accountType==='FUNDED'&&!phaseId){setTrades([]);return}let active=true;setLoading(true);setError('');const base={startDate:from,endDate:to,limit:100,sortBy:'tradeDate',sortOrder:'asc',...(phaseId?{phaseId}:{})};api.get(`/accounts/${accountId}/trades`,{params:{...base,page:1}}).then(async({data})=>{const first=data.data,pages=first.pagination.totalPages,rest=pages>1?await Promise.all(Array.from({length:pages-1},(_,index)=>api.get(`/accounts/${accountId}/trades`,{params:{...base,page:index+2}}))):[];if(active)setTrades([...(first.items||[]),...rest.flatMap((response)=>response.data.data.items||[])])}).catch((reason)=>{if(active){setTrades([]);setError(errorMessage(reason))}}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[accountId,phaseId,account?.accountType,from,to]);
  const data=useMemo(()=>calendarData(month,trades),[month,trades]),tradingDays=data.days.filter((day)=>day.trades),winningDays=tradingDays.filter((day)=>day.net>0),losingDays=tradingDays.filter((day)=>day.net<0),breakEvenDays=tradingDays.filter((day)=>day.net===0),monthlyNet=tradingDays.reduce((sum,day)=>sum+day.net,0),bestDay=[...tradingDays].sort((a,b)=>b.net-a.net)[0],worstDay=[...tradingDays].sort((a,b)=>a.net-b.net)[0],today=dateKey(new Date()),selectedDay=data.days.find((day)=>day.key===selectedDayKey)||null,selectedTrades=selectedDayKey?trades.filter((trade)=>String(trade.tradeDate).slice(0,10)===selectedDayKey):[];
  const move=(offset)=>setMonth((current)=>new Date(current.getFullYear(),current.getMonth()+offset,1));
  const openDay=(day)=>day.trades&&setSelectedDayKey(day.key);
  const journalUrl=(trade)=>journalDrillDownUrl({accountId,phaseId,from:selectedDayKey,to:selectedDayKey,journalFilter:trade?{search:trade.tradeNumber}:{}});
  const summary=[['Monthly Net P&L',money(monthlyNet,currency),monthlyNet<0?'loss':'profit'],['Trading Days',tradingDays.length],['Winning Days',winningDays.length,'profit'],['Losing Days',losingDays.length,'loss'],['Break-even Days',breakEvenDays.length],['Best Trading Day',bestDay?`${bestDay.day} · ${money(bestDay.net,currency)}`:'—','profit'],['Worst Trading Day',worstDay?`${worstDay.day} · ${money(worstDay.net,currency)}`:'—',worstDay?.net<0?'loss':undefined]];
  return <main className="mx-auto max-w-[1700px] space-y-5 px-5 py-7 lg:px-8"><ActiveAccountIndicator/>{!accountId?<MissingActiveAccount/>:account?.accountType==='FUNDED'&&!phaseId?<section className="card flex min-h-72 items-center justify-center p-8 text-center text-muted">Select an active funded phase to view its trading calendar.</section>:<>
    <section className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><p className="text-xs font-medium uppercase tracking-[.2em] text-lime">Monthly analytics</p><h1 className="mt-2 text-3xl font-semibold">Trading Calendar</h1><p className="mt-2 text-sm text-muted">Visual overview of your trading activity across each month.</p></div><div className="card flex items-center justify-between gap-2 p-2"><button className="btn-secondary px-3" onClick={()=>move(-1)} aria-label="Previous month"><ChevronLeft size={17}/><span className="hidden sm:inline">Previous Month</span></button><p className="min-w-36 text-center text-sm font-semibold">{month.toLocaleDateString('en-US',{month:'long',year:'numeric'})}</p><button className="btn-secondary px-3" onClick={()=>move(1)} aria-label="Next month"><span className="hidden sm:inline">Next Month</span><ChevronRight size={17}/></button></div></section>
    {error&&<section className="card border-rose-500/30 p-4 text-sm text-rose-400">{error}</section>}
    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4 2xl:grid-cols-7">{summary.map(([label,value,tone])=><MetricCard key={label} label={label} value={loading?'…':value} tone={tone}/>)}</section>
    <section className="card p-5"><div className="mb-4"><h2 className="text-lg font-semibold">Weekly Summary</h2><p className="mt-1 text-xs text-muted">Calendar weeks within the selected month.</p></div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{data.weeks.map((week)=>{const current=week.days.some((day)=>day.key===today);return <article className={`rounded-xl border p-4 ${current?'border-lime/40 bg-lime/[.055] shadow-[0_0_18px_rgba(199,243,107,.07)]':'border-line bg-ink/25'}`} key={week.index}><div className="flex items-center justify-between"><p className="font-semibold">Week {week.index}</p>{current&&<span className="rounded-full bg-lime/10 px-2 py-0.5 text-[10px] font-medium uppercase tracking-wider text-lime">Current</span>}</div><dl className="mt-4 grid grid-cols-2 gap-x-4 gap-y-3 text-xs"><div><dt className="text-muted">Net P&amp;L</dt><dd className={week.net<0?'mt-1 font-semibold text-rose-400':'mt-1 font-semibold text-lime'}>{money(week.net,currency)}</dd></div><div><dt className="text-muted">Trading days</dt><dd className="mt-1 font-semibold">{week.tradingDays}</dd></div><div><dt className="text-muted">Win rate</dt><dd className="mt-1 font-semibold">{week.winRate==null?'—':`${number(week.winRate,1)}%`}</dd></div><div><dt className="text-muted">Trades</dt><dd className="mt-1 font-semibold">{week.trades}</dd></div><div><dt className="text-muted">Best day</dt><dd className="mt-1 font-semibold">{week.bestDay?`${week.bestDay.day} · ${money(week.bestDay.net,currency)}`:'—'}</dd></div><div><dt className="text-muted">Worst day</dt><dd className="mt-1 font-semibold">{week.worstDay?`${week.worstDay.day} · ${money(week.worstDay.net,currency)}`:'—'}</dd></div></dl></article>})}</div></section>
    <section className="card p-4 sm:p-5"><div className="mb-4 flex items-center justify-between"><div><h2 className="text-lg font-semibold">Month Calendar</h2><p className="mt-1 text-xs text-muted">Monday through Sunday · select a trading day to review trades.</p></div><CalendarDays className="text-lime" size={22}/></div>{!loading&&!trades.length&&<div className="mb-4 rounded-xl border border-dashed border-line bg-ink/25 p-5 text-center text-sm text-muted">No trading activity during this month.</div>}<div className="performance-scrollbar overflow-x-auto pb-2"><div className="min-w-[840px]"><div className="grid grid-cols-7 gap-2">{DAY_NAMES.map((name)=><div className="px-2 py-2 text-center text-xs font-medium uppercase tracking-wider text-muted" key={name}>{name}</div>)}{data.cells.map((day,index)=>day?<button key={day.key} disabled={!day.trades} onMouseEnter={()=>day.trades&&setHovered(day)} onMouseLeave={()=>setHovered(null)} onFocus={()=>day.trades&&setHovered(day)} onBlur={()=>setHovered(null)} onClick={()=>openDay(day)} className={`flex min-h-32 flex-col rounded-xl border p-3 text-left transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-lime ${day.net>0?'border-lime/30 bg-lime/[.055] shadow-[0_0_16px_rgba(199,243,107,.06)] hover:border-lime/55':day.net<0?'border-rose-400/30 bg-rose-400/[.055] shadow-[0_0_16px_rgba(251,113,133,.06)] hover:border-rose-400/55':day.trades?'border-slate-500/35 bg-slate-500/[.055] hover:border-slate-400/55':'cursor-default border-line bg-ink/20'} ${day.key===today?'ring-1 ring-lime/45':''}`}><span className="text-xs font-semibold text-slate-300">{day.day}</span><span className={`my-auto self-center text-sm font-semibold ${day.net>0?'text-lime':day.net<0?'text-rose-400':'text-slate-300'}`}>{day.trades?(day.net===0?'BE':money(day.net,currency)):'No Trades'}</span><span className="text-[11px] text-muted">{day.trades?`${day.trades} ${day.trades===1?'Trade':'Trades'}`:'No journal entries'}</span></button>:<div className="min-h-32 rounded-xl border border-transparent bg-white/[.01]" key={`empty-${index}`}/>)}</div></div></div></section>
    <DayTooltip day={hovered} currency={currency}/>
    <DayTradeDrawer day={selectedDay} trades={selectedTrades} currency={currency} onClose={()=>setSelectedDayKey(null)} onOpenTrade={(trade)=>history.push(journalUrl(trade))}/>
  </>}</main>;
}
