import { Router } from 'express';
import * as controller from '../controllers/accountController.js';
import * as trades from '../controllers/tradeController.js';
import * as csv from '../controllers/csvController.js';
import { asyncHandler } from '../utils/asyncHandler.js';
import { validate } from '../middleware/validate.js';
import { accountRules, idParam } from '../validators/accountValidators.js';
import { tradeRules } from '../validators/tradeValidators.js';
import { csvUpload } from '../middleware/upload.js';
import * as phases from '../controllers/phaseController.js';
import { phaseRules } from '../validators/phaseValidators.js';

const router = Router();
router.get('/', asyncHandler(controller.listAccounts));
router.post('/', accountRules, validate, asyncHandler(controller.createAccount));
router.get('/:id', idParam(), validate, asyncHandler(controller.getAccount));
router.put('/:id', idParam(), validate, asyncHandler(controller.updateAccount));
router.patch('/:accountId', idParam('accountId'), validate, asyncHandler(controller.updateAccount));
router.delete('/:id', idParam(), validate, asyncHandler(controller.deleteAccount));
router.post('/:id/archive', idParam(), validate, asyncHandler(controller.archiveAccount));
router.post('/:id/restore', idParam(), validate, asyncHandler(controller.restoreAccount));
router.post('/:id/reactivate', idParam(), validate, asyncHandler(controller.reactivateAccount));
router.get('/:id/statistics', idParam(), validate, asyncHandler(controller.statistics));
router.get('/:id/balance-history', idParam(), validate, asyncHandler(controller.balanceHistory));
router.get('/:id/markets', idParam(), validate, asyncHandler(controller.markets));
router.get('/:id/analytics/markets', idParam(), validate, asyncHandler(controller.marketsAnalytics));
router.get('/:id/journal/filter-options', idParam(), validate, asyncHandler(controller.filterOptions));
router.get('/:accountId/trades', idParam('accountId'), validate, asyncHandler(trades.list));
router.get('/:accountId/trades/ids', idParam('accountId'), validate, asyncHandler(trades.ids));
router.post('/:accountId/trades', idParam('accountId'), tradeRules, validate, asyncHandler(trades.create));
router.post('/:accountId/trades/import/preview', idParam('accountId'), validate, csvUpload.single('file'), asyncHandler(csv.preview));
router.post('/:accountId/trades/import/confirm', idParam('accountId'), validate, asyncHandler(csv.confirm));
router.get('/:accountId/phases', idParam('accountId'), validate, asyncHandler(phases.list));
router.post('/:accountId/phases', idParam('accountId'), phaseRules, validate, asyncHandler(phases.create));
export default router;
