import { useEffect, useState } from 'react';
import { Download, Upload } from 'lucide-react';
import Modal from '../ui/Modal.jsx';
import { api, errorMessage } from '../../api/client.js';

export default function CsvImportModal({ open, accountId, account, phaseId, onClose, onImported, notify }) {
  const [preview,setPreview]=useState(null),[busy,setBusy]=useState(false),[importSummary,setImportSummary]=useState(null);
  useEffect(()=>{if(!open){setPreview(null);setImportSummary(null);}},[open]);
  const upload=async(file)=>{if(!file)return;setBusy(true);try{const body=new FormData();body.append('file',file);const {data}=await api.post(`/accounts/${accountId}/trades/import/preview`,body);setPreview(data.data);}catch(e){notify(errorMessage(e),'error');}finally{setBusy(false);}};
  const confirm=async()=>{setBusy(true);try{const rows=preview.rows.filter((row)=>row.valid).map((row)=>row.data);const {data}=await api.post(`/accounts/${accountId}/trades/import/confirm`,{rows,sourceSummary:preview.summary,phaseId});notify(data.message);setImportSummary(data.data.summary);onImported();}catch(e){notify(errorMessage(e),'error');}finally{setBusy(false);}};
  const download=async()=>{const response=await api.get('/trades/csv-template',{responseType:'blob'});const url=URL.createObjectURL(response.data),anchor=document.createElement('a');anchor.href=url;anchor.download='trading-journal-template.csv';anchor.click();URL.revokeObjectURL(url);};
  const formatLabel=preview?.format==='EXNESS'?'Exness export detected':preview?.format==='METATRADER'?'MT4 / MT5 / FundedNext export detected':'Trading Singularity template detected';
  return <Modal open={open} onClose={onClose} title="Import trades from CSV" subtitle="Trading Singularity, Exness, MT4, MT5 and FundedNext formats are detected automatically." wide>
    {account?.accountType==='FUNDED'&&<div className="mb-4 rounded-xl border border-lime/30 bg-lime/5 p-3 text-sm">Destination: <strong>{account.phases?.find((item)=>item.id===phaseId)?.name||'Select a phase'}</strong>.</div>}
    <div className="flex flex-wrap gap-3"><label className="btn-primary cursor-pointer"><Upload size={16}/>{busy?'Processing…':'Choose CSV'}<input className="hidden" type="file" accept=".csv,text/csv" disabled={busy} onChange={(e)=>upload(e.target.files[0])}/></label><button className="btn-secondary" onClick={download}><Download size={16}/> Download template</button></div>
    {importSummary?<div className="mt-6"><h3 className="text-lg font-semibold">Import complete</h3><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[['Total detected',importSummary.totalDetected],['Imported',importSummary.imported],['Skipped empty',importSummary.skippedEmpty],['Duplicates',importSummary.duplicates],['Failed rows',importSummary.failedRows]].map(([label,value])=><div key={label} className="rounded-xl border border-line bg-ink/50 p-4"><p className="text-xs uppercase tracking-wider text-muted">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p></div>)}</div><div className="mt-6 flex justify-end"><button className="btn-primary" onClick={onClose}>Done</button></div></div>
    :preview&&<div className="mt-5"><div className="mb-3 flex flex-wrap gap-3 text-sm"><span className="rounded bg-sky-500/10 px-3 py-1 text-sky-300">{formatLabel}</span><span className="rounded bg-white/5 px-3 py-1">Detected {preview.summary.totalDetected}</span><span className="rounded bg-lime/10 px-3 py-1 text-lime">Valid {preview.summary.valid}</span></div>
      <div className="scrollbar max-h-80 overflow-auto rounded-xl border border-line"><table className="w-full min-w-[1200px] text-left text-xs"><thead className="sticky top-0 bg-[#171d27]"><tr><th className="p-3">Row</th><th>Status</th><th>Source</th><th>Strategy</th><th>Market</th><th>Planned RR</th><th>Realized R</th><th>Risk %</th><th>P&L</th><th>Warnings / errors</th></tr></thead><tbody className="divide-y divide-line">{preview.rows.map((row)=><tr key={row.rowNumber}><td className="p-3">{row.rowNumber}</td><td className={row.valid?'text-lime':'text-rose-400'}>{row.valid?'Valid':'Invalid'}</td><td>{row.data.importSource}</td><td>{row.data.strategyName||'-'}</td><td>{row.data.market}</td><td>{row.data.plannedRR??'—'}</td><td>{row.data.realizedRMultiple??'—'}</td><td>{row.data.riskPercentage??'—'}</td><td>{row.data.profitLoss}</td><td className="max-w-96 text-amber-300" title={row.data.calculationWarnings?.join('\n')}>{[...row.errors,...(row.data.calculationWarnings||[])].join('; ')||'—'}</td></tr>)}</tbody></table></div>
      <div className="mt-5 flex justify-end gap-3"><button className="btn-secondary" onClick={onClose}>Cancel</button><button className="btn-primary" disabled={busy||!preview.summary.valid} onClick={confirm}>{busy?'Importing…':`Import ${preview.summary.valid} valid rows`}</button></div>
    </div>}
  </Modal>;
}
